config/routes.rb
Rails.application.routes.draw do
  root to: 'reviews#index' 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:show, :new, :create] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :user
  def self.search(search)
    # Review.where('tmdb_id LIKE(?)', '%#{search}%')
    # Review.where('tmdb_id LIKE(?)', '%1%')
    Review.where(tmdb_id: "#{search}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
  end
  def create
    Review.create(review_params)
    redirect_to root_path
  end

  def search
    @reviews = Review.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def review_params
    params.require(:review).permit(:tmdb_id, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pickinema</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.haml
.head
  %link{href:"https://fonts.googleapis.com/css?family=PT+Sans|M+PLUS+Rounded+1c&display=swap", rel:"stylesheet"}
.nav_bar

.main
  .main__center
    .main__center__poster__left
      .main__center__poster__left__writedreview
      =image_tag src=""
      -# =form_with url: "/reviews/search", method: :GET, local: true do |form|
      =form_with url: "/reviews/search", id: "search-engine", method: :GET, local: true do |form|
        =form.text_field :keyword, class: "search-reviews"
        =form.submit "SEARCH", id: "search-btn"
    -# .main__center__poster__left__review

    .main__center__poster__btn
      #firstword
        本日の映画をランダムピック
      .box-3
        .btn.btn-three
          %span
            Pickinema!!
    
    .main__center__poster__left__info
      .main__center__poster__left__info-title
      .main__center__poster__left__info-releasedate
      .main__center__poster__left__info-overview

    .main__center__poster__left__review
      =form_with url: reviews_path, id: "review-body", method: :POST, model: Review.new, local: true do |form|  
        =form.text_field :tmdb_id, id: "main__center__poster__left__form__tmdb_id", placeholder: "mtdb_id"
        =form.text_area :body, id: "main__center__poster__left__form__review", placeholder: "Write your review"
        =form.submit "SEND", id: "submit_left" 

app/views/reviews/search.html.haml
.seikou
  これでどうですか！！
  